# Base configs
baseurl: "MostlyStark.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Andres Torres"
subtitle: "See the world through my eyes!"
author: "Andres Torres"
header:
 title: "Photography"
 subtitle: "by Andres Torres"
footer:
 name: "Hey there, my name is Drem"
 bio: "I am a developer and a tech aficionado from Detroit. Love making teeny tiny apps solving tiny problems in life."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/NoGoodTweets"
  instagram: "https://www.instagram.com/NoGoodPhotos"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/AndresECTorres"
  github: "https://www.github.com/MostlyStark"
